/**
 * Sentinel Guard (v2.0)
 * 
 * Multi-layer OS-level package manager interception:
 * 1. PATH-based wrappers (~/.sentinel/bin/*) — harder to bypass
 * 2. Shell profile PATH prepend to ensure wrappers are found first
 * 3. Legacy shell aliases (fallback)
 * 
 * Makes Sentinel ineludible — even when the user types 'npm install' directly.
 */

import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';

export const SUPPORTED_MANAGERS = ['npm', 'pip', 'pip3', 'yarn', 'pnpm', 'cargo', 'docker'];

function getSentinelBinDir(): string {
    return path.join(os.homedir(), '.sentinel', 'bin');
}

export function getShellProfilePath(): string {
    const shell = process.env.SHELL || '';
    if (shell.includes('zsh')) return path.join(os.homedir(), '.zshrc');
    if (shell.includes('fish')) return path.join(os.homedir(), '.config/fish/config.fish');
    
    // PowerShell (Windows)
    if (process.platform === 'win32') {
        return path.join(os.homedir(), 'Documents', 'WindowsPowerShell', 'Microsoft.PowerShell_profile.ps1');
    }
    return path.join(os.homedir(), '.bashrc');
}

function getShellRcPath(): string {
    const shell = process.env.SHELL || '';
    if (shell.includes('zsh')) return path.join(os.homedir(), '.zshenv');
    if (shell.includes('fish')) return path.join(os.homedir(), '.config/fish/config.fish');
    if (process.platform === 'win32') return getShellProfilePath(); // PowerShell
    return path.join(os.homedir(), '.bashrc');
}

function generateWrapperScript(manager: string, platform: string): string {
    const exeMap: Record<string, string> = {
        'npm': 'npm.cmd', 'yarn': 'yarn.cmd', 'pnpm': 'pnpm.cmd',
        'pip': 'pip.exe', 'pip3': 'pip3.exe',
        'cargo': 'cargo.exe', 'docker': 'docker.exe'
    };

    if (platform === 'win32') {
        const exe = exeMap[manager] || `${manager}.exe`;
        // PowerShell wrapper
        return `# Sentinel Guard wrapper for ${manager}
# This file is auto-generated by sentinel guard enable
param(
    [Parameter(ValueFromRemainingArguments=$true)]
    [string[]]$args
)
sentinel install ${manager} @args
if ($LASTEXITCODE -eq 0) {
    & "${exe}" @args
}
`;
    } else {
        // Unix shell wrapper
        return `#!/bin/sh
# Sentinel Guard wrapper for ${manager}
exec sentinel install ${manager} "$@" && exec ${manager} "$@"
`;
    }
}

function generatePathExportLine(): string {
    const binDir = getSentinelBinDir();
    const shell = process.env.SHELL || '';
    if (shell.includes('fish')) {
        return `set -gx PATH '${binDir}' $PATH`;
    }
    if (process.platform === 'win32') {
        return `$env:PATH = '${binDir};' + $env:PATH`;
    }
    return `export PATH="${binDir}:$PATH"`;
}

function installWrapperScripts(): void {
    const binDir = getSentinelBinDir();
    if (!fs.existsSync(binDir)) {
        fs.mkdirSync(binDir, { recursive: true });
    }

    for (const mgr of SUPPORTED_MANAGERS) {
        const scriptPath = path.join(binDir, mgr);
        const content = generateWrapperScript(mgr, process.platform);
        fs.writeFileSync(scriptPath, content, { mode: 0o755 });

        // On Windows, also create a .cmd file for cmd.exe
        if (process.platform === 'win32') {
            const cmdPath = path.join(binDir, `${mgr}.cmd`);
            const cmdContent = `@echo off
rem Sentinel Guard wrapper for ${mgr}
sentinel install ${mgr} %*
if %ERRORLEVEL% EQU 0 (
    ${mgr}.cmd %*
)
`;
            fs.writeFileSync(cmdPath, cmdContent);
        }
    }
}

function removeWrapperScripts(): void {
    const binDir = getSentinelBinDir();
    for (const mgr of SUPPORTED_MANAGERS) {
        const scriptPath = path.join(binDir, mgr);
        try { fs.unlinkSync(scriptPath); } catch (_) {}
        if (process.platform === 'win32') {
            try { fs.unlinkSync(path.join(binDir, `${mgr}.cmd`)); } catch (_) {}
        }
    }
}

function generateUnixAliases(): string {
    return SUPPORTED_MANAGERS.map(mgr => {
        return [
            `# Sentinel Guard: ${mgr} interception`,
            `sentinel_${mgr}() {`,
            `  sentinel install ${mgr} "$@" && \\`,
            `  command ${mgr} "$@"`,
            `}`,
            `alias ${mgr}='sentinel_${mgr}'`
        ].join('\n');
    }).join('\n\n');
}

function generatePowerShellAliases(): string {
    const exeMap: Record<string, string> = {
        'npm': 'npm.cmd', 'yarn': 'yarn.cmd', 'pnpm': 'pnpm.cmd',
        'pip': 'pip.exe', 'pip3': 'pip3.exe',
        'cargo': 'cargo.exe', 'docker': 'docker.exe'
    };
    return SUPPORTED_MANAGERS.map(mgr => {
        const exe = exeMap[mgr] || `${mgr}.exe`;
        return [
            `# Sentinel Guard: ${mgr} interception`,
            `function ${mgr} {`,
            `  sentinel install ${mgr} $args`,
            `  if ($LASTEXITCODE -eq 0) { & "${exe}" $args }`,
            `}`
        ].join('\n');
    }).join('\n\n');
}

const SENTINEL_GUARD_BLOCK_START = '# ====== SENTINEL GUARD START ======';
const SENTINEL_GUARD_BLOCK_END   = '# ====== SENTINEL GUARD END ======';

export interface GuardResult {
    success: boolean;
    reason?: string;
    profilePath?: string;
    managers?: string[];
}

export function enableGuard(): GuardResult {
    const profilePath = getShellProfilePath();
    const isWindows = process.platform === 'win32';
    
    // Step 1: Install PATH-based wrapper scripts
    installWrapperScripts();
    
    // Step 2: Add PATH export to profile (before aliases block)
    const pathLine = generatePathExportLine();
    const pathFlag = '# SENTINEL GUARD PATH';
    
    // Step 3: Legacy aliases (backup for when PATH wrappers are bypassed)
    const aliases = isWindows ? generatePowerShellAliases() : generateUnixAliases();
    const guardBlock = `\n${pathFlag}\n${pathLine}\n${SENTINEL_GUARD_BLOCK_START}\n${aliases}\n${SENTINEL_GUARD_BLOCK_END}\n`;

    let existing = '';
    try { existing = fs.readFileSync(profilePath, 'utf8'); } catch (_e1: unknown) {}

    if (existing.includes(SENTINEL_GUARD_BLOCK_START)) {
        return { success: false, reason: 'Guard is already enabled.', profilePath };
    }

    const dir = path.dirname(profilePath);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(profilePath, existing + guardBlock);
    
    return { success: true, profilePath, managers: SUPPORTED_MANAGERS };
}

export function disableGuard(): GuardResult {
    const profilePath = getShellProfilePath();
    let existing = '';
    try { existing = fs.readFileSync(profilePath, 'utf8'); } catch (_e2: unknown) {
        return { success: false, reason: 'Shell profile not found.' };
    }

    // Remove PATH export
    const pathFlag = '# SENTINEL GUARD PATH';
    const pathIdx = existing.indexOf(pathFlag);
    if (pathIdx !== -1) {
        const pathEnd = existing.indexOf('\n', pathIdx + 1);
        if (pathEnd !== -1) {
            existing = existing.slice(0, pathIdx) + existing.slice(pathEnd + 1);
        }
    }

    // Remove alias block
    const startIdx = existing.indexOf(SENTINEL_GUARD_BLOCK_START);
    const endIdx   = existing.indexOf(SENTINEL_GUARD_BLOCK_END);
    
    if (startIdx === -1) {
        // Still remove wrapper scripts even if alias block wasn't found
        removeWrapperScripts();
        return { success: false, reason: 'Guard is not enabled.' };
    }
    
    const cleaned = existing.slice(0, startIdx) + existing.slice(endIdx + SENTINEL_GUARD_BLOCK_END.length);
    fs.writeFileSync(profilePath, cleaned.replace(/\n{3,}/g, '\n\n'));
    
    // Remove wrapper scripts
    removeWrapperScripts();
    
    return { success: true, profilePath };
}

export function isGuardEnabled(): boolean {
    try {
        const profilePath = getShellProfilePath();
        const content = fs.readFileSync(profilePath, 'utf8');
        return content.includes(SENTINEL_GUARD_BLOCK_START);
    } catch (_e3: unknown) { return false; }
}
