import { AgencyScoreResult } from '../../core/agency_score';
import { EvidenceCard } from '../../core/evidence_card';

function severityBadge(severity: string): string {
  switch (severity) {
    case 'CRITICAL': return '🔴 CRITICAL';
    case 'HIGH': return '🟡 HIGH';
    case 'MEDIUM': return '🔵 MEDIUM';
    default: return '⚪ LOW';
  }
}

function verdictBadge(verdict: string): string {
  switch (verdict) {
    case 'BLOCK': return '🔴 BLOCK';
    case 'REVIEW': return '🟡 REVIEW';
    default: return '🟢 PASS';
  }
}

function blastRadiusBadge(br: string): string {
  switch (br) {
    case 'CRITICAL': return '🔴 CRITICAL';
    case 'HIGH': return '🟡 HIGH';
    case 'MEDIUM': return '🟠 MEDIUM';
    default: return '🟢 LOW';
  }
}

export function renderMarkdown(
  findingsCount: number,
  agency: AgencyScoreResult,
  cards: EvidenceCard[],
): string {
  const lines: string[] = [];

  lines.push('## Sentinel Agency Score Report');
  lines.push('');

  lines.push('| Metric | Value |');
  lines.push('|--------|-------|');
  lines.push(`| **Agency Score** | ${agency.agencyScore}/100 |`);
  lines.push(`| **Verdict** | ${verdictBadge(agency.verdict)} |`);
  lines.push(`| **Blast Radius** | ${blastRadiusBadge(agency.blastRadius)} |`);
  lines.push(`| **Total Findings** | ${agency.totalFindings} |`);
  lines.push(`| **Critical** | ${agency.criticalCount} |`);
  lines.push(`| **High** | ${agency.highCount} |`);
  lines.push('');

  if (agency.drivers.length > 0) {
    lines.push('### Top Drivers');
    lines.push('');
    lines.push('| Contribution | Subcode | Title |');
    lines.push('|-------------|---------|-------|');
    for (const d of agency.drivers.slice(0, 5)) {
      const contrib = d.contribution >= 30 ? `**+${d.contribution}**` : `+${d.contribution}`;
      lines.push(`| ${contrib} | \`${d.subcode}\` | ${d.title} |`);
    }
    lines.push('');
  }

  if (cards.length > 0) {
    lines.push('### Evidence Cards');
    lines.push('');

    for (const card of cards) {
      lines.push(`<details>`);
      lines.push(`<summary><strong>${severityBadge(card.severity)}</strong> ${card.title} ${card.contribution ? `(+${card.contribution})` : ''}</summary>`);
      lines.push('');
      lines.push(`**Subcode:** \`${card.subcode}\``);
      lines.push(`**File:** \`${card.file}:${card.line}\``);
      lines.push(`**Category:** ${card.category}`);
      lines.push(`**Risk Score:** ${card.riskScore}/100`);
      lines.push(`**Confidence:** ${card.confidence.toUpperCase()}`);
      if (card.description) lines.push(`**Description:** ${card.description}`);
      if (card.evidence) lines.push(`**Evidence:** \`${card.evidence}\``);
      if (card.recommendation) lines.push(`**Fix:** ${card.recommendation}`);
      lines.push('');
      lines.push(`</details>`);
      lines.push('');
    }
  }

  lines.push('---');
  lines.push(`_Report generated by Sentinel v4.0.0_`);

  return lines.join('\n');
}
