import { describe, it, expect } from 'vitest'
import { LockfileParser, LockfileEntry, LockfileResult } from './lockfile_parser'

function makeParser(): LockfileParser {
  return new LockfileParser()
}

describe('LockfileParser', () => {
  describe('detectFormat', () => {
    it('detects npm v7+ format', () => {
      const parser = makeParser()
      const content = JSON.stringify({ packages: { 'node_modules/foo': { version: '1.0.0' } } })
      expect(parser.detectFormat(content)).toBe('npm-v7')
    })

    it('detects npm v6 format', () => {
      const parser = makeParser()
      const content = JSON.stringify({ dependencies: { foo: { version: '1.0.0' } } })
      expect(parser.detectFormat(content)).toBe('npm-v6')
    })

    it('detects yarn format', () => {
      const parser = makeParser()
      const content = [
        '# THIS IS AN AUTOGENERATED FILE',
        '',
        'foo@^1.0.0:',
        '  version "1.0.0"',
      ].join('\n')
      expect(parser.detectFormat(content)).toBe('yarn')
    })

    it('returns unknown for empty content', () => {
      const parser = makeParser()
      expect(parser.detectFormat('')).toBe('unknown')
      expect(parser.detectFormat('   ')).toBe('unknown')
    })

    it('returns unknown for unrecognized content', () => {
      const parser = makeParser()
      expect(parser.detectFormat('garbage')).toBe('unknown')
    })
  })

  describe('parsePackageLock - npm v7+ format', () => {
    const v7Content = JSON.stringify({
      name: 'test-app',
      lockfileVersion: 2,
      packages: {
        '': {
          name: 'test-app',
          version: '1.0.0',
        },
        'node_modules/express': {
          version: '4.18.2',
          resolved: 'https://registry.npmjs.org/express/-/express-4.18.2.tgz',
          integrity: 'sha512-5yGi0rNScBPYrsDlTnE5N8wL6WxHjV9BRHrH2IymX+JShy2+3fD3S6vC2j1F/LpGMkZLsO3W5DGb4PLOq8ZNw==',
          dependencies: {
            accepts: '^1.3.8',
            'array-flatten': '1.1.1',
          },
        },
        'node_modules/accepts': {
          version: '1.3.8',
          resolved: 'https://registry.npmjs.org/accepts/-/accepts-1.3.8.tgz',
          integrity: 'sha512-PYAthAg2P2GUIDDt3T8vCVN5s4UQ9pNdR3Tpf7k2Gc6EExoGT2cV7XHc1LVvB/aNaEIkFkOYxkNzX6zErjK0g==',
          dependencies: {
            'mime-types': '~2.1.34',
            negotiator: '0.6.3',
          },
        },
        'node_modules/array-flatten': {
          version: '1.1.1',
          resolved: 'https://registry.npmjs.org/array-flatten/-/array-flatten-1.1.1.tgz',
          integrity: 'sha512-PCVAQswWemu6UdxsDFFX/+gXh2FYR2W4GsTp1IE9fM4s7V6D8Z7J7KnxcN2g2vhLxo5R74A5cR1f5H7CF2q3A==',
        },
        'node_modules/@scope/pkg': {
          version: '2.1.0',
          resolved: 'https://registry.npmjs.org/@scope/pkg/-/pkg-2.1.0.tgz',
          integrity: 'sha512-abc123==',
          dependencies: {
            lodash: '^4.17.21',
          },
        },
        'node_modules/lodash': {
          version: '4.17.21',
          resolved: 'https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz',
          integrity: 'sha512-v2kDEe57lecTulaDIuNTPy3Ry4gLGJ6Z0O4Z+2z3Tjxz8K9V0QeHaL+aQTz6oF1Q/lZQEjJN6U7s1KJVViVlg==',
        },
      },
    })

    it('parses v7+ and returns correct format', () => {
      const parser = makeParser()
      const result = parser.parsePackageLock(v7Content)
      expect(result.format).toBe('npm-v7')
    })

    it('parses 5 entries excluding root', () => {
      const parser = makeParser()
      const result = parser.parsePackageLock(v7Content)
      expect(result.entries).toHaveLength(5)
    })

    it('extracts scoped package names correctly', () => {
      const parser = makeParser()
      const result = parser.parsePackageLock(v7Content)
      const scoped = result.entries.find(e => e.name === '@scope/pkg')
      expect(scoped).toBeDefined()
      expect(scoped!.version).toBe('2.1.0')
    })

    it('extracts versions correctly', () => {
      const parser = makeParser()
      const result = parser.parsePackageLock(v7Content)
      const express = result.entries.find(e => e.name === 'express')
      expect(express).toBeDefined()
      expect(express!.version).toBe('4.18.2')
    })

    it('extracts transitive dependencies', () => {
      const parser = makeParser()
      const result = parser.parsePackageLock(v7Content)
      const express = result.entries.find(e => e.name === 'express')!
      expect(express.dependencies).toContain('accepts')
      expect(express.dependencies).toContain('array-flatten')

      const accepts = result.entries.find(e => e.name === 'accepts')!
      expect(accepts.dependencies).toContain('mime-types')
      expect(accepts.dependencies).toContain('negotiator')
    })

    it('extracts resolved and integrity fields', () => {
      const parser = makeParser()
      const result = parser.parsePackageLock(v7Content)
      const express = result.entries.find(e => e.name === 'express')!
      expect(express.resolved).toContain('registry.npmjs.org')
      expect(express.integrity).toContain('sha512')
    })
  })

  describe('parsePackageLock - npm v6 format', () => {
    const v6Content = JSON.stringify({
      name: 'test-app',
      version: '1.0.0',
      lockfileVersion: 1,
      dependencies: {
        express: {
          version: '4.18.2',
          resolved: 'https://registry.npmjs.org/express/-/express-4.18.2.tgz',
          integrity: 'sha512-sha1...',
          dependencies: {
            accepts: {
              version: '1.3.8',
            },
          },
        },
        lodash: {
          version: '4.17.21',
          resolved: 'https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz',
          integrity: 'sha512-v2k...',
        },
        chalk: {
          version: '5.3.0',
          resolved: 'https://registry.npmjs.org/chalk/-/chalk-5.3.0.tgz',
          integrity: 'sha512-dT...',
        },
      },
    })

    it('parses v6 and returns correct format', () => {
      const parser = makeParser()
      const result = parser.parsePackageLock(v6Content)
      expect(result.format).toBe('npm-v6')
    })

    it('parses 3 entries', () => {
      const parser = makeParser()
      const result = parser.parsePackageLock(v6Content)
      expect(result.entries).toHaveLength(3)
    })

    it('extracts names and versions', () => {
      const parser = makeParser()
      const result = parser.parsePackageLock(v6Content)
      const express = result.entries.find(e => e.name === 'express')!
      expect(express.version).toBe('4.18.2')
      const lodash = result.entries.find(e => e.name === 'lodash')!
      expect(lodash.version).toBe('4.17.21')
      const chalk = result.entries.find(e => e.name === 'chalk')!
      expect(chalk.version).toBe('5.3.0')
    })

    it('extracts v6 transitive deps from nested object keys', () => {
      const parser = makeParser()
      const result = parser.parsePackageLock(v6Content)
      const express = result.entries.find(e => e.name === 'express')!
      expect(express.dependencies).toContain('accepts')
    })
  })

  describe('parseYarnLock', () => {
    const yarnContent = [
      '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.',
      '# yarn lockfile v1',
      '',
      'express@^4.18.0, express@^4.18.2:',
      '  version "4.18.2"',
      '  resolved "https://registry.npmjs.org/express/-/express-4.18.2.tgz#abc123"',
      '  integrity sha512-5yGi0rNScBPYrsDlTnE5N8wL6WxHjV9BRHrH2IymX+JShy2+3fD3S6vC2j1F/LpGMkZLsO3W5DGb4PLOq8ZNw==',
      '  dependencies:',
      '    accepts "^1.3.8"',
      '    array-flatten "1.1.1"',
      '',
      'accepts@^1.3.8:',
      '  version "1.3.8"',
      '  resolved "https://registry.npmjs.org/accepts/-/accepts-1.3.8.tgz#def456"',
      '  integrity sha512-PYAthAg2P2GUIDDt3T8vCVN5s4UQ9pNdR3Tpf7k2Gc6EExoGT2cV7XHc1LVvB/aNaEIkFkOYxkNzX6zErjK0g==',
      '  dependencies:',
      '    mime-types "~2.1.34"',
      '    negotiator "0.6.3"',
      '',
      '@scope/pkg@^2.0.0:',
      '  version "2.1.0"',
      '  resolved "https://registry.npmjs.org/@scope/pkg/-/pkg-2.1.0.tgz#ghi789"',
      '  integrity sha512-abc123==',
      '  dependencies:',
      '    lodash "^4.17.21"',
    ].join('\n')

    it('parses yarn format', () => {
      const parser = makeParser()
      const result = parser.parseYarnLock(yarnContent)
      expect(result.format).toBe('yarn')
    })

    it('parses 3 entries', () => {
      const parser = makeParser()
      const result = parser.parseYarnLock(yarnContent)
      expect(result.entries).toHaveLength(3)
    })

    it('extracts scoped package from yarn', () => {
      const parser = makeParser()
      const result = parser.parseYarnLock(yarnContent)
      const scoped = result.entries.find(e => e.name === '@scope/pkg')
      expect(scoped).toBeDefined()
      expect(scoped!.version).toBe('2.1.0')
    })

    it('extracts versions correctly', () => {
      const parser = makeParser()
      const result = parser.parseYarnLock(yarnContent)
      const express = result.entries.find(e => e.name === 'express')!
      expect(express.version).toBe('4.18.2')
      const accepts = result.entries.find(e => e.name === 'accepts')!
      expect(accepts.version).toBe('1.3.8')
    })

    it('extracts dependency lists from yarn', () => {
      const parser = makeParser()
      const result = parser.parseYarnLock(yarnContent)
      const express = result.entries.find(e => e.name === 'express')!
      expect(express.dependencies).toContain('accepts')
      expect(express.dependencies).toContain('array-flatten')
      const accepts = result.entries.find(e => e.name === 'accepts')!
      expect(accepts.dependencies).toContain('mime-types')
    })
  })

  describe('error handling', () => {
    it('returns empty for empty package-lock', () => {
      const parser = makeParser()
      const result = parser.parsePackageLock('{}')
      expect(result.entries).toHaveLength(0)
      expect(result.format).toBe('unknown')
    })

    it('returns empty for malformed JSON', () => {
      const parser = makeParser()
      const result = parser.parsePackageLock('not json')
      expect(result.entries).toHaveLength(0)
      expect(result.format).toBe('unknown')
    })

    it('returns empty for unknown format parse', () => {
      const parser = makeParser()
      const result = parser.parsePackageLock('{"unknown": true}')
      expect(result.entries).toHaveLength(0)
      expect(result.format).toBe('unknown')
    })

    it('parse returns empty for non-existent file', () => {
      const parser = makeParser()
      const result = parser.parse('C:\\nonexistent\\path\\lockfile.json')
      expect(result.entries).toHaveLength(0)
      expect(result.format).toBe('unknown')
    })

    it('parses malformed yarn gracefully', () => {
      const parser = makeParser()
      const result = parser.parseYarnLock('')
      expect(result.entries).toHaveLength(0)
      expect(result.format).toBe('yarn')
    })
  })

  describe('realistic sample (npm v7+)', () => {
    const realisticLock = JSON.stringify({
      name: 'my-project',
      version: '2.1.0',
      lockfileVersion: 3,
      packages: {
        '': { name: 'my-project', version: '2.1.0' },
        'node_modules/react': {
          version: '18.3.1',
          resolved: 'https://registry.npmjs.org/react/-/react-18.3.1.tgz',
          integrity: 'sha512-wS+hAgJShR0KhEvPJArfuPVN1+Hz1t0Y6n5jLr4Qb6n1F7M01C0D5GNUfc8E5UqeeoE2mzEj9W2ZfJ6EERfM9w==',
          dependencies: {
            'loose-envify': '^1.1.0',
          },
        },
        'node_modules/loose-envify': {
          version: '1.4.0',
          resolved: 'https://registry.npmjs.org/loose-envify/-/loose-envify-1.4.0.tgz',
          integrity: 'sha512-lyuxPGr/Wfhrlem2CL/UcnUcS0NOHT+b2+e/JjN4GlSgLUKkag2HOKqM2Jhm8+Q6lMEn1s7C5wZXW8kQ==',
          dependencies: {
            js: '^1.0.0',
          },
        },
        'node_modules/js': {
          version: '1.0.0',
          resolved: 'https://registry.npmjs.org/js/-/js-1.0.0.tgz',
          integrity: 'sha512-xyz789=',
        },
        'node_modules/@types/react': {
          version: '19.0.0',
          resolved: 'https://registry.npmjs.org/@types/react/-/react-19.0.0.tgz',
          integrity: 'sha512-abc123def456=',
        },
      },
    })

    it('parses 4 entries from realistic sample', () => {
      const parser = makeParser()
      const result = parser.parsePackageLock(realisticLock)
      expect(result.entries).toHaveLength(4)
    })

    it('extracts react version 18.3.1', () => {
      const parser = makeParser()
      const result = parser.parsePackageLock(realisticLock)
      const react = result.entries.find(e => e.name === 'react')
      expect(react).toBeDefined()
      expect(react!.version).toBe('18.3.1')
    })

    it('extracts loose-envify as a dependency of react', () => {
      const parser = makeParser()
      const result = parser.parsePackageLock(realisticLock)
      const react = result.entries.find(e => e.name === 'react')!
      expect(react.dependencies).toContain('loose-envify')
    })

    it('correctly marks root node_modules/@types/react as @types/react', () => {
      const parser = makeParser()
      const result = parser.parsePackageLock(realisticLock)
      const typesReact = result.entries.find(e => e.name === '@types/react')
      expect(typesReact).toBeDefined()
      expect(typesReact!.version).toBe('19.0.0')
    })
  })
})
